/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author valdo
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {//Método construtor. Mostra a fala padrão do gênio no balão de fala ao iniciar o programa.
        initComponents();
        lblFala.setText("<html>Vou pensar em um número de <strong>1 a 5</strong>. Tente adivinhar!</html>");//Tag html para quebra de linha no lblFala. O strong serve para deixar em negrito.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPalpite = new javax.swing.JButton();
        spnNumero = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 80, -1));

        spnNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 40, -1));

        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 37, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/akinator.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lblFala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFala.setText("Fala");
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/speech balloon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        double numero = 1 + Math.random() * (6 - 1);//Sorteia um número entre 1 a 5 e armazena na variável "numero". É o número em que o gênio pensou;
        int numeroGenio = (int) numero;//Armazena na variável "numeroGenio" como um valor inteiro o número em que o gênio pensou.
        
        int numeroPalpite = Integer.parseInt(spnNumero.getValue().toString());//Armazena na variável "numeroPalpite" o número que o usuário informou no "spnNumero".
        
        String falaAcerto = "<html>ACERTOU!</html>";//Caso o usuário informe um número igual ao que o gênio pensou.
        String falaErro = "<html>ERROU! Eu pensei no número " + numeroGenio + "</html>";//Caso o usuário informe um número diferente do que o gênio pensou.
        
        String resultado = (numeroGenio == numeroPalpite)?falaAcerto:falaErro;//Se o usuário inseriu no spnNumero o mesmo número que o gênio pensou, a "falaAcerto" será atribuida a variável "resultado", senão, será a "falaErro".
        
        lblFala.setText(resultado);//Mostra no "lblFala" se o usuário acertou ou errou o número que o gênio pensou.
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFala;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
